--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: discountms
    version: v1
  name: discountms
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: discountms
      version: v1
  template: 
    metadata: 
      labels: 
        app: discountms
        version: v1

    spec: 

      containers: 
        - 
          image: "prabhakarm/discountmsvirtual:1"
          imagePullPolicy: Always
          name: discountms  
          env:
            - name: discountms.configserverurl
              value: "http://configserver:8888"
            - name: discountms.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    